---
version: 1.0.0
slug: yandexdns
name: Yandex DNS
description: >-
  Yandex DNS
url: https://github.com/ponyatovu/home-assistant
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
image: homeassistant/{arch}-addon-yandexdns
map:
  - ssl:rw
options:
  domains:
    - null
  token: null
  aliases: []
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
  seconds: 300
schema:
  domains:
    - match(.+\.yandex\.net)
  token: str
  aliases:
    - alias: str
      domain: str
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
  seconds: int
  ipv4: str?
  ipv6: str?
startup: services
