---
version: 1.0.0
slug: yandexdns
name: Yandex DNS
description: >-
  Yandex DNS
url: https://github.com/ponyatovu/home-assistant
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
options:
  domain: null
  subdomain: null
  token: null
  seconds: 300
schema:
  domain: str
  subdomain: str
  token: str
  seconds: int
startup: services
