---
version: 1.0.4
slug: yandexdns
name: Yandex DNS
description: >-
  Updating your IP in Yandex DNS
url: https://github.com/ponyatovu/home-assistant
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
options:
  domain: 'shome.kz'
  subdomain: 'ha01'
  token: '6TRQZ65JXMROEY273ZAWGYUDPEZT56ZYNIYDTBJD3VHIL6SL3TYA'
  seconds: 300
  debug: 1
schema:
  domain: str
  subdomain: str
  token: str
  seconds: int
  debug: int
startup: services
